sudo: required

language: bash

services:
  - docker

before_install:
  - docker pull koalaman/shellcheck

script:
  - docker run koalaman/shellcheck --version
  - docker run -v $(pwd):/scripts koalaman/shellcheck --color=always --external-sources /scripts/glsysbackup
  - docker run -v $(pwd):/scripts koalaman/shellcheck --color=always /scripts/glsysbackup.inc.sh

matrix:
  fast_finish: true

notifications:
  email: false
