language: bash

sudo: required

services:
  - docker

before_install:
  - docker pull koalaman/shellcheck

script:
 - bash -c 'shopt -s globstar; shellcheck **/glsysbackup'

matrix:
  fast_finish: true
